server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:brokerage
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        security: DEBUG
